version: '3.9'
services:
  #
  #  db:
  #    image: mysql:latest
  #    volumes:
  #      - "./.mysql-data/db:/var/lib/mysql"
  #    restart: always
  #    ports:
  #      - 3306:3306
  #    environment:
  #      MYSQL_ROOT_PASSWORD: root
  #      MYSQL_DATABASE: testDB
  #      MYSQL_USER: root
  #      MYSQL_PASSWORD: password
  postgres_db:
    image: postgres:latest
    container_name: PostgresCont
    restart: always
    environment:
      - POSTGRES_USER=keshav
      - POSTGRES_PASSWORD=keshav
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: onlyshafcs@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres_db:
  pgadmin-data: